import type { Garage, Review } from '@/types'

export const mockGarages: Garage[] = [
  {
    id: '1',
    name: 'Garage Van den Berg',
    slug: 'garage-van-den-berg',
    address: 'Hertogsingel 45',
    city: 'Maastricht',
    kvk_number: '12345678',
    kvk_verified: true,
    description: 'Al meer dan 25 jaar uw betrouwbare partner voor autoonderhoud in Maastricht. Wij werken met alle merken en zijn gespecialiseerd in APK-keuringen, onderhoud en bandenservice. Ons team van ervaren monteurs staat voor u klaar.\n\nAls enige garage in de regio bieden wij ook service in het Engels en Frans aan, ideaal voor expats en internationale bezoekers. Wij geloven in transparante communicatie: u krijgt altijd een duidelijke uitleg en offerte voordat we beginnen.',
    phone: '043-321-4567',
    email: 'info@garagevandenb.nl',
    website: 'www.garagevandenb.nl',
    plan: 'premium',
    rating: 4.8,
    review_count: 64,
    services: ['APK', 'Onderhoud', 'Banden', 'Airco', 'Schade', 'Electrisch'],
    languages: ['Nederlands', 'Engels', 'Frans'],
    hours: [
      { day: 1, open: '08:00', close: '17:30', closed: false },
      { day: 2, open: '08:00', close: '17:30', closed: false },
      { day: 3, open: '08:00', close: '17:30', closed: false },
      { day: 4, open: '08:00', close: '17:30', closed: false },
      { day: 5, open: '08:00', close: '17:00', closed: false },
      { day: 6, open: '09:00', close: '13:00', closed: false },
      { day: 0, open: '', close: '', closed: true },
    ],
    photos: [],
    created_at: '2024-01-15',
    is_open: true,
  },
  {
    id: '2',
    name: 'AutoService Janssen',
    slug: 'autoservice-janssen',
    address: 'Boschstraat 112',
    city: 'Maastricht',
    kvk_number: '23456789',
    kvk_verified: true,
    description: 'AutoService Janssen is een familiebedrijf met meer dan 40 jaar ervaring. Wij zijn gespecialiseerd in Europese merken en bieden een volledig servicepakket aan. Van kleine reparaties tot grote revisies, u kunt bij ons terecht.',
    phone: '043-456-7890',
    email: 'info@autoservicejanssen.nl',
    website: 'www.autoservicejanssen.nl',
    plan: 'free',
    rating: 4.5,
    review_count: 38,
    services: ['APK', 'Onderhoud', 'Remmen', 'Uitlaat', 'Elektrisch'],
    languages: ['Nederlands', 'Duits'],
    hours: [
      { day: 1, open: '07:30', close: '18:00', closed: false },
      { day: 2, open: '07:30', close: '18:00', closed: false },
      { day: 3, open: '07:30', close: '18:00', closed: false },
      { day: 4, open: '07:30', close: '18:00', closed: false },
      { day: 5, open: '07:30', close: '17:30', closed: false },
      { day: 6, open: '08:00', close: '12:00', closed: false },
      { day: 0, open: '', close: '', closed: true },
    ],
    photos: [],
    created_at: '2024-02-10',
    is_open: true,
  },
  {
    id: '3',
    name: 'Peters Autospecialisten',
    slug: 'peters-autospecialisten',
    address: 'Tongerseplein 8',
    city: 'Maastricht',
    kvk_number: '34567890',
    kvk_verified: true,
    description: 'Peters Autospecialisten staat bekend om onze eerlijke prijzen en vakkundige service. Wij zijn gespecialiseerd in schadewerk en spuiterij, maar doen ook regulier onderhoud. Expats zijn altijd welkom — we spreken vloeiend Engels.',
    phone: '043-567-8901',
    email: 'info@petersauto.nl',
    website: 'www.petersauto.nl',
    plan: 'premium',
    rating: 4.6,
    review_count: 52,
    services: ['APK', 'Schade', 'Spuiterij', 'Onderhoud', 'Banden'],
    languages: ['Nederlands', 'Engels'],
    hours: [
      { day: 1, open: '08:00', close: '17:00', closed: false },
      { day: 2, open: '08:00', close: '17:00', closed: false },
      { day: 3, open: '08:00', close: '17:00', closed: false },
      { day: 4, open: '08:00', close: '17:00', closed: false },
      { day: 5, open: '08:00', close: '17:00', closed: false },
      { day: 6, open: '', close: '', closed: true },
      { day: 0, open: '', close: '', closed: true },
    ],
    photos: [],
    created_at: '2024-03-01',
    is_open: false,
  },
  {
    id: '4',
    name: 'Maastricht Autocentrum',
    slug: 'maastricht-autocentrum',
    address: 'Akersteenweg 78',
    city: 'Maastricht',
    kvk_number: '45678901',
    kvk_verified: false,
    description: 'Maastricht Autocentrum is uw one-stop-shop voor alles wat met uw auto te maken heeft. Van APK tot airco, van banden tot uitlaat. Snel, betrouwbaar en betaalbaar.',
    phone: '043-678-9012',
    email: 'info@maastrichtauto.nl',
    website: 'www.maastrichtauto.nl',
    plan: 'free',
    rating: 4.1,
    review_count: 27,
    services: ['APK', 'Onderhoud', 'Airco', 'Banden', 'Uitlaat'],
    languages: ['Nederlands'],
    hours: [
      { day: 1, open: '08:30', close: '17:30', closed: false },
      { day: 2, open: '08:30', close: '17:30', closed: false },
      { day: 3, open: '08:30', close: '17:30', closed: false },
      { day: 4, open: '08:30', close: '17:30', closed: false },
      { day: 5, open: '08:30', close: '17:00', closed: false },
      { day: 6, open: '', close: '', closed: true },
      { day: 0, open: '', close: '', closed: true },
    ],
    photos: [],
    created_at: '2024-04-05',
    is_open: true,
  },
  {
    id: '5',
    name: 'Smeets Garage & Occasionhandel',
    slug: 'smeets-garage',
    address: 'Wilhelminasingel 33',
    city: 'Maastricht',
    kvk_number: '56789012',
    kvk_verified: true,
    description: 'Bij Smeets Garage combineert u onderhoud met occasionhandel. Wij onderhouden uw huidige auto en helpen u ook bij aankoop van een betrouwbare occasion. Altijd transparant, altijd eerlijk.',
    phone: '043-789-0123',
    email: 'info@smeetsgarage.nl',
    website: 'www.smeetsgarage.nl',
    plan: 'business',
    rating: 4.9,
    review_count: 91,
    services: ['APK', 'Onderhoud', 'Banden', 'Occasionhandel', 'Remmen', 'Airco'],
    languages: ['Nederlands', 'Engels', 'Duits', 'Frans'],
    hours: [
      { day: 1, open: '08:00', close: '18:00', closed: false },
      { day: 2, open: '08:00', close: '18:00', closed: false },
      { day: 3, open: '08:00', close: '18:00', closed: false },
      { day: 4, open: '08:00', close: '18:00', closed: false },
      { day: 5, open: '08:00', close: '18:00', closed: false },
      { day: 6, open: '09:00', close: '15:00', closed: false },
      { day: 0, open: '', close: '', closed: true },
    ],
    photos: [],
    created_at: '2023-11-20',
    is_open: true,
  },
]

export const mockReviews: Review[] = [
  {
    id: '1',
    garage_id: '1',
    user_id: 'u1',
    user_name: 'James Wilson',
    user_country: 'GB',
    is_expat: true,
    rating: 5,
    text: 'Excellent service! As an expat I was worried about language barriers but the team spoke perfect English. Fair prices, quick turnaround on my APK. Will definitely return.',
    language: 'en',
    verified: true,
    created_at: '2024-05-12',
    ratings: [
      { category: 'eerlijkheid', score: 5 },
      { category: 'prijs', score: 5 },
      { category: 'snelheid', score: 5 },
      { category: 'communicatie', score: 5 },
      { category: 'engels', score: 5 },
    ],
    reply: {
      id: 'r1',
      text: 'Bedankt James! Het was een plezier u te helpen. U bent altijd welkom!',
      created_at: '2024-05-13',
    },
  },
  {
    id: '2',
    garage_id: '1',
    user_id: 'u2',
    user_name: 'Sophie de Vries',
    is_expat: false,
    rating: 5,
    text: 'Al jaren kom ik hier. Altijd eerlijk advies, nooit onnodig werk aangeraden. De monteurs leggen goed uit wat ze doen. Aanrader!',
    language: 'nl',
    verified: true,
    created_at: '2024-04-28',
    ratings: [
      { category: 'eerlijkheid', score: 5 },
      { category: 'prijs', score: 4 },
      { category: 'snelheid', score: 5 },
      { category: 'communicatie', score: 5 },
      { category: 'engels', score: 4 },
    ],
  },
  {
    id: '3',
    garage_id: '1',
    user_id: 'u3',
    user_name: 'Marco Rossi',
    user_country: 'IT',
    is_expat: true,
    rating: 4,
    text: 'Good garage, honest pricing. They fixed my brakes quickly. Only minor issue was waiting time for appointment but quality was excellent.',
    language: 'en',
    verified: true,
    created_at: '2024-04-15',
    ratings: [
      { category: 'eerlijkheid', score: 5 },
      { category: 'prijs', score: 4 },
      { category: 'snelheid', score: 3 },
      { category: 'communicatie', score: 4 },
      { category: 'engels', score: 5 },
    ],
  },
  {
    id: '4',
    garage_id: '2',
    user_id: 'u4',
    user_name: 'Petra Willems',
    is_expat: false,
    rating: 4,
    text: 'Goede garage, vriendelijk personeel. Mijn auto was snel klaar. Prijs was iets hoger dan verwacht maar kwaliteit is er.',
    language: 'nl',
    verified: true,
    created_at: '2024-05-01',
    ratings: [
      { category: 'eerlijkheid', score: 4 },
      { category: 'prijs', score: 3 },
      { category: 'snelheid', score: 5 },
      { category: 'communicatie', score: 4 },
      { category: 'engels', score: 3 },
    ],
  },
  {
    id: '5',
    garage_id: '5',
    user_id: 'u5',
    user_name: 'Anna Müller',
    user_country: 'DE',
    is_expat: true,
    rating: 5,
    text: 'Hervorragender Service! Das Team spricht auch Deutsch, was sehr angenehm war. Faire Preise und schnelle Arbeit. Sehr empfehlenswert!',
    language: 'de',
    verified: true,
    created_at: '2024-05-20',
    ratings: [
      { category: 'eerlijkheid', score: 5 },
      { category: 'prijs', score: 5 },
      { category: 'snelheid', score: 5 },
      { category: 'communicatie', score: 5 },
      { category: 'engels', score: 5 },
    ],
  },
]

export const SERVICES = [
  'APK', 'Onderhoud', 'Banden', 'Airco', 'Schade', 'Spuiterij',
  'Remmen', 'Uitlaat', 'Elektrisch', 'Electrisch', 'Occasionhandel',
]

export const LANGUAGES = ['Nederlands', 'Engels', 'Duits', 'Frans', 'Turks', 'Arabisch']

// Weergavelabels voor Engelse pagina's — de waarden zelf (SERVICES/LANGUAGES) blijven Nederlands,
// want dat zijn de letterlijke opgeslagen waarden in garage_services/garage_languages waarop
// gefilterd wordt. Alleen het label dat de gebruiker ziet wordt vertaald.
export const SERVICE_LABELS_EN: Record<string, string> = {
  APK: 'APK',
  Onderhoud: 'Maintenance',
  Banden: 'Tyres',
  Airco: 'AC',
  Schade: 'Bodywork',
  Spuiterij: 'Paintwork',
  Remmen: 'Brakes',
  Uitlaat: 'Exhaust',
  Elektrisch: 'Electrical',
  Electrisch: 'Electrical',
  Occasionhandel: 'Used car sales',
}

export const LANGUAGE_LABELS_EN: Record<string, string> = {
  Nederlands: 'Dutch',
  Engels: 'English',
  Duits: 'German',
  Frans: 'French',
  Turks: 'Turkish',
  Arabisch: 'Arabic',
}

export const DAY_NAMES = ['Zondag', 'Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag']
export const DAY_NAMES_EN = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
